print(36)
print(7+4)
print(2*4.5)
print(17-0.3)
print(9**2)
print(9//2)
print(15 % 2)
print(12.5+4.6)
print(9.5 % 3)
print("I'm famous")
print('Widziałem "słonia"')
print("ma"*2)
print("dsfd\"")
print('na'*20 + 'Batman')
print(12*"Aa")
print("Nowy film Ama'deusza pt. \"xyx\"")
print("A\\A'==A\\A\"")
print(input('podaj rozmiar swojego buta: '))
print('Lubię jeść: ' + input('co lubisz jeść? '))
print(input('ile liter ma twoje imie')*5)
